/*
 * Copyright (c) 2012 - 2024 Data In Motion and others.
 * All rights reserved. 
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *      Mark Hoffmann - initial API and implementation
 */
package org.hl7.fhir;

import org.osgi.annotation.versioning.ProviderType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Account Balance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * A financial tool for tracking value accrued for a particular purpose.  In the healthcare field, used to track charges for a patient, cost centers, etc.
 * <!-- end-model-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.hl7.fhir.AccountBalance#getAggregate <em>Aggregate</em>}</li>
 *   <li>{@link org.hl7.fhir.AccountBalance#getTerm <em>Term</em>}</li>
 *   <li>{@link org.hl7.fhir.AccountBalance#getEstimate <em>Estimate</em>}</li>
 *   <li>{@link org.hl7.fhir.AccountBalance#getAmount <em>Amount</em>}</li>
 * </ul>
 *
 * @see org.hl7.fhir.FHIRPackage#getAccountBalance()
 * @model extendedMetaData="name='Account.Balance' kind='elementOnly'"
 * @generated
 */
@ProviderType
public interface AccountBalance extends BackboneElement {
	/**
	 * Returns the value of the '<em><b>Aggregate</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Who is expected to pay this part of the balance.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Aggregate</em>' containment reference.
	 * @see #setAggregate(CodeableConcept)
	 * @see org.hl7.fhir.FHIRPackage#getAccountBalance_Aggregate()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='aggregate' namespace='##targetNamespace'"
	 * @generated
	 */
	CodeableConcept getAggregate();

	/**
	 * Sets the value of the '{@link org.hl7.fhir.AccountBalance#getAggregate <em>Aggregate</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Aggregate</em>' containment reference.
	 * @see #getAggregate()
	 * @generated
	 */
	void setAggregate(CodeableConcept value);

	/**
	 * Returns the value of the '<em><b>Term</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * The term of the account balances - The balance value is the amount that was outstanding for this age.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Term</em>' containment reference.
	 * @see #setTerm(CodeableConcept)
	 * @see org.hl7.fhir.FHIRPackage#getAccountBalance_Term()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='term' namespace='##targetNamespace'"
	 * @generated
	 */
	CodeableConcept getTerm();

	/**
	 * Sets the value of the '{@link org.hl7.fhir.AccountBalance#getTerm <em>Term</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Term</em>' containment reference.
	 * @see #getTerm()
	 * @generated
	 */
	void setTerm(CodeableConcept value);

	/**
	 * Returns the value of the '<em><b>Estimate</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * The amount is only an estimated value - this is likely common for `current` term balances, but not with known terms (that were generated by a backend process).
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Estimate</em>' containment reference.
	 * @see #setEstimate(org.hl7.fhir.Boolean)
	 * @see org.hl7.fhir.FHIRPackage#getAccountBalance_Estimate()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='estimate' namespace='##targetNamespace'"
	 * @generated
	 */
	org.hl7.fhir.Boolean getEstimate();

	/**
	 * Sets the value of the '{@link org.hl7.fhir.AccountBalance#getEstimate <em>Estimate</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Estimate</em>' containment reference.
	 * @see #getEstimate()
	 * @generated
	 */
	void setEstimate(org.hl7.fhir.Boolean value);

	/**
	 * Returns the value of the '<em><b>Amount</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * The actual balance value calculated for the age defined in the term property.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Amount</em>' containment reference.
	 * @see #setAmount(Money)
	 * @see org.hl7.fhir.FHIRPackage#getAccountBalance_Amount()
	 * @model containment="true" required="true"
	 *        extendedMetaData="kind='element' name='amount' namespace='##targetNamespace'"
	 * @generated
	 */
	Money getAmount();

	/**
	 * Sets the value of the '{@link org.hl7.fhir.AccountBalance#getAmount <em>Amount</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Amount</em>' containment reference.
	 * @see #getAmount()
	 * @generated
	 */
	void setAmount(Money value);

} // AccountBalance
