/*
 * Copyright (c) 2012 - 2024 Data In Motion and others.
 * All rights reserved. 
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *      Mark Hoffmann - initial API and implementation
 */
package org.hl7.fhir;

import org.osgi.annotation.versioning.ProviderType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Genomic Study Input</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * A GenomicStudy is a set of analyses performed to analyze and generate genomic data.
 * <!-- end-model-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.hl7.fhir.GenomicStudyInput#getFile <em>File</em>}</li>
 *   <li>{@link org.hl7.fhir.GenomicStudyInput#getType <em>Type</em>}</li>
 *   <li>{@link org.hl7.fhir.GenomicStudyInput#getGeneratedByIdentifier <em>Generated By Identifier</em>}</li>
 *   <li>{@link org.hl7.fhir.GenomicStudyInput#getGeneratedByReference <em>Generated By Reference</em>}</li>
 * </ul>
 *
 * @see org.hl7.fhir.FHIRPackage#getGenomicStudyInput()
 * @model extendedMetaData="name='GenomicStudy.Input' kind='elementOnly'"
 * @generated
 */
@ProviderType
public interface GenomicStudyInput extends BackboneElement {
	/**
	 * Returns the value of the '<em><b>File</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * File containing input data.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>File</em>' containment reference.
	 * @see #setFile(Reference)
	 * @see org.hl7.fhir.FHIRPackage#getGenomicStudyInput_File()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='file' namespace='##targetNamespace'"
	 * @generated
	 */
	Reference getFile();

	/**
	 * Sets the value of the '{@link org.hl7.fhir.GenomicStudyInput#getFile <em>File</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>File</em>' containment reference.
	 * @see #getFile()
	 * @generated
	 */
	void setFile(Reference value);

	/**
	 * Returns the value of the '<em><b>Type</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Type of input data, e.g., BAM, CRAM, or FASTA.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Type</em>' containment reference.
	 * @see #setType(CodeableConcept)
	 * @see org.hl7.fhir.FHIRPackage#getGenomicStudyInput_Type()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='type' namespace='##targetNamespace'"
	 * @generated
	 */
	CodeableConcept getType();

	/**
	 * Sets the value of the '{@link org.hl7.fhir.GenomicStudyInput#getType <em>Type</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Type</em>' containment reference.
	 * @see #getType()
	 * @generated
	 */
	void setType(CodeableConcept value);

	/**
	 * Returns the value of the '<em><b>Generated By Identifier</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Generated By Identifier</em>' containment reference.
	 * @see #setGeneratedByIdentifier(Identifier)
	 * @see org.hl7.fhir.FHIRPackage#getGenomicStudyInput_GeneratedByIdentifier()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='generatedByIdentifier' namespace='##targetNamespace'"
	 * @generated
	 */
	Identifier getGeneratedByIdentifier();

	/**
	 * Sets the value of the '{@link org.hl7.fhir.GenomicStudyInput#getGeneratedByIdentifier <em>Generated By Identifier</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Generated By Identifier</em>' containment reference.
	 * @see #getGeneratedByIdentifier()
	 * @generated
	 */
	void setGeneratedByIdentifier(Identifier value);

	/**
	 * Returns the value of the '<em><b>Generated By Reference</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Generated By Reference</em>' containment reference.
	 * @see #setGeneratedByReference(Reference)
	 * @see org.hl7.fhir.FHIRPackage#getGenomicStudyInput_GeneratedByReference()
	 * @model containment="true"
	 *        extendedMetaData="kind='element' name='generatedByReference' namespace='##targetNamespace'"
	 * @generated
	 */
	Reference getGeneratedByReference();

	/**
	 * Sets the value of the '{@link org.hl7.fhir.GenomicStudyInput#getGeneratedByReference <em>Generated By Reference</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Generated By Reference</em>' containment reference.
	 * @see #getGeneratedByReference()
	 * @generated
	 */
	void setGeneratedByReference(Reference value);

} // GenomicStudyInput
