<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="basisbehoerde" nsURI="http://xoev.de/schemata/basisnachricht/behoerde/1_0"
    nsPrefix="basisbehoerde">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Diese Schema-Datei enthält die technische Repräsentation der in der DIN SPEC 91379 definierten Datentypen."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="BehoerdeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Dieser Typ enthält Angaben zur Identifikation einer Behörde / öffentlichen Stelle in einem Verzeichnisdienst sowie ihrer Erreichbarkeit."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="BehoerdeType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verzeichnisdienst" lowerBound="1"
        eType="#//CodeVerzeichnisdienstType" containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Angabe des Verzeichnisdienstes (bspw. DVDV), in welchem die Behörde / öffentliche Stelle unter der nachfolgend angegebenen Kennung eingetragen ist."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="verzeichnisdienst"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kennung" lowerBound="1"
        eType="ecore:EDataType ../../de.xoev.din91379/model/din-91379-1903.ecore#//DatatypeC">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Dieses Element enthält die eindeutige Kennzeichnung der Behörde / öffentlichen Stelle innerhalb des angegebenen Verzeichnisdienstes. Für den Verzeichnisdienst „DVDV“ enthält die Kennzeichnung das „Präfix“ und die „Kennung“ getrennt durch das Zeichen ':', also bspw. 'psw:01003110'."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="kennung"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType ../../de.xoev.din91379/model/din-91379-1903.ecore#//DatatypeC">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Dieses Element enthält den Namen der Behörde / öffentlichen Stelle."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="name"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="erreichbarkeit" upperBound="-1"
        eType="ecore:EClass basisnachricht-kommunikation.ecore#//KommunikationType"
        containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Angaben zur Erreichbarkeit dieser Behörde per Telefon, Telefax, E-Mail etc."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="erreichbarkeit"/>
        <details key="namespace" value="http://xoev.de/schemata/basisnachricht/kommunikation/1_0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeVerzeichnisdienstType" eSuperTypes="../../de.xoev.code/model/xoev-code.ecore#//Code">
    <eAnnotations>
      <details key="appinfo" value="&#xA;              &#xA;  &lt;codeliste>&#xA;                   &#xA;    &lt;nameLang>Verzeichnisdienst&#xA;&lt;/nameLang>&#xA;                   &#xA;    &lt;nameKurz>Verzeichnisdienst&#xA;&lt;/nameKurz>&#xA;                   &#xA;    &lt;nameTechnisch>verzeichnisdienst&lt;/nameTechnisch>&#xA;                   &#xA;    &lt;kennung>urn:xoev-de:kosit:codeliste:verzeichnisdienst&lt;/kennung>&#xA;                   &#xA;    &lt;beschreibung>Liste der Verzeichnisdienste, in die Behörden / öffentliche Stellen eingetragen sein können&lt;/beschreibung>&#xA;                   &#xA;    &lt;herausgebernameLang>Koordinierungsstelle für IT-Standards&lt;/herausgebernameLang>&#xA;                   &#xA;    &lt;herausgebernameKurz>KoSIT&lt;/herausgebernameKurz>&#xA;                &#xA;  &lt;/codeliste>&#xA;           &#xA;"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Code.VerzeichnisdienstType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
